include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**
    - web/**
    - linux/**
    - macos/**
    - windows/**

  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
    unnecessary_null_comparison: warning

linter:
  rules:

    # ======================================
    # CODE STYLE
    # ======================================
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    require_trailing_commas: true

    # ======================================
    # CLEAN CODE
    # ======================================
    avoid_print: true
    avoid_unnecessary_containers: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true

    # ======================================
    # PERFORMANCE
    # ======================================
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true

    # ======================================
    # SAFETY
    # ======================================
    avoid_empty_else: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true

    # ======================================
    # BEST PRACTICES
    # ======================================
    directives_ordering: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    unnecessary_lambdas: true
    unnecessary_string_interpolations: true

    # ======================================
    # NAMING
    # ======================================
    camel_case_types: true
    file_names: true
    non_constant_identifier_names: false

    # ======================================
    # DOCUMENTATION
    # ======================================
    public_member_api_docs: false